version: '3.7'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    networks: 
      - node-webapp-network
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - PORT=4000
    ports:
      - 4005:4005
    networks:
      - node-webapp-network
volumes:
  mongo-data:
    driver: local
networks:
  node-webapp-network:
    driver: bridge